eureka:
  instance:
    hostname: localhost
    port: 8082
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
server:
  port: 8083
  session:
    timeout: 600

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ia-test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    platform: posgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: POSTGRESQL
    show-sql: true
  session:
    store-type: redis
  redis:
    host: localhost
    password:
    port: 6379